#!/bin/bash

# Exit on command errors and treat unset variables as an error
set -eu

# Source YunoHost helpers
source /usr/share/yunohost/helpers

app=$YNH_APP_INSTANCE_NAME

domain=$YNH_APP_ARG_DOMAIN
path=$YNH_APP_ARG_PATH
contact=$YNH_APP_ARG_CONTACT
is_public=$YNH_APP_ARG_IS_PUBLIC
secret=$(ynh_string_random 24)
src_path=/var/www/$app
port=8081
while ! sudo yunohost app checkport $port ; do
    port=$((port+1))
done
dir=$(pwd)

# Save app settings
ynh_app_setting_set "$app" version "7db7688b"
ynh_app_setting_set "$app" is_public "$is_public"
ynh_app_setting_set "$app" secret "$secret"

# Check domain/path availability
sudo yunohost app checkurl "${domain}${path}" -a "$app" \
    || ynh_die "Path not available: ${domain}${path}"

# Install dependencies
if ! ynh_package_is_installed "build-essential" ; then
     ynh_package_install build-essential
fi
if ! ynh_package_is_installed "libssl-dev" ; then
     ynh_package_install libssl-dev
fi
echo "yes" | sudo cpan Carton

# Create user
if ! ynh_system_user_exists "$app" ; then
    sudo adduser $app --home $src_path --no-create-home --disabled-password --gecos $app
fi

# Copy source files
sudo git clone https://framagit.org/luc/lufi.git $src_path
cd $src_path
sudo carton install
sudo cp lufi.conf.template lufi.conf
sudo chown -R $app: $src_path

# Configure
sudo sed -e "s@listen *=>.*@listen => ['http://127.0.0.1:$port'],@" \
         -e "s@#proxy *=>.*@proxy  => 1,@" \
         -e "s@#contact *=>.*@contact       => '$contact',@" \
         -e "s@#secrets *=>.*@secrets        => ['$secret'],@" \
         -e "s@#prefix *=>.*@prefix        => '$path',@" \
         -i lufi.conf

sudo cp utilities/lufi.service /etc/systemd/system/
sudo sed -e "s@User=www-data@User=$app@" \
         -e "s@WorkingDirectory=/var/www/lufi/@WorkingDirectory=$src_path@" \
         -e "s@PIDFile=/var/www/lufi/script/hypnotoad.pid@PIDFile=$src_path/script/hypnotoad.pid@" \
         -i /etc/systemd/system/lufi.service

sudo systemctl daemon-reload
sudo systemctl enable lufi.service

# Start
sudo systemctl start lufi.service

# Modify Nginx configuration file and copy it to Nginx conf directory
cd $dir
nginx_conf=../conf/nginx.conf
sed -i "s@YNH_WWW_PATH@$path@g" $nginx_conf
sed -i "s@YNH_LUFI_PORT@$port/@g" $nginx_conf
sudo cp $nginx_conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [[ $is_public -eq 1 ]]; then
    # unprotected_uris allows SSO credentials to be passed anyway.
    ynh_app_setting_set "$app" unprotected_uris "/"
fi

domainregex=$(echo "$domain" | sed 's/-/\%&/g')
pathregex=$(echo "$path" | sed 's/-/\%&/g')
ynh_app_setting_set "$app" skipped_regex "$domainregex$pathregex/r/","$domainregex$pathregex/about","$domainregex$pathregex/download"
# Reload services
sudo service nginx reload
